apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "caluma.fullname" . }}-backend
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "caluma.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "caluma.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.backend.repository }}:version-{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DATABASE_HOST
            value: "{{ template "caluma.fullname" . }}-postgresql"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            value: "{{ .Values.postgresql.postgresqlUsername }}"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "caluma.fullname" . }}-postgresql"
                key: postgresql-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ template "caluma.fullname" . }}-backend"
                key: secretkey
          - name: ALLOWED_HOSTS
            value: "*"
          - name: VISIBILITY_CLASSES
            value: "caluma.core.visibilities.Any"
          - name: PERMISSION_CLASSES
            value: "caluma.core.permissions.AllowAny"
{{- if .Values.minio.enabled }}
          - name: MINIO_STORAGE_ENDPOINT
            value: "{{ index .Values.minio.ingress.hosts 0 }}"
          - name: MINIO_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ template "caluma.fullname" . }}-minio"
                key: accesskey
          - name: MINIO_STORAGE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ template "caluma.fullname" . }}-minio"
                key: secretkey
          - name: MINIO_STORAGE_USE_HTTPS
            value: "{{ if ne (len .Values.minio.ingress.tls) 0 }}true{{ else }}false{{ end }}"
{{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
