{{- /*
TODO: get rid of this as quickly as possible!!!
Currently it is required because the caluma-demo has this hostname hardcoded in
configuration and won't start if it can't resolve the hostname caluma
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: caluma
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "caluma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
