# Default values for caluma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  backend:
    repository: projectcaluma/caluma
    # TODO: discuss if we want to solely pull based on AppVersion or if we want
    # to support tag too.
    #tag: version-2.0.0
    pullPolicy: IfNotPresent
  frontend:
    repository: projectcaluma/caluma-demo
    tag: stable
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secretKey: "SUPERSECRET"

service:
  type: ClusterIP
  # TODO: provide ability to configure service for frontend and backend
  # separately
  #port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: caluma.chart-example.local

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  postgresqlDatabase: caluma
  postgresqlUsername: caluma
  postgresqlPassword: CHANGEME

##
## MinIO chart configuration
##
## https://github.com/helm/charts/blob/master/stable/minio/values.yaml
##
minio:
  ## Caluma relies on MinIO for persistency of uploads. If you need to handle
  ## uploads in your forms you need to enable the MinIO chart and configure
  ## ingress for external access.
  enabled: false
  accessKey: ""
  secretKey: ""
  defaultBucket:
    enabled: true
    name: caluma-media
    # TODO: review MinIO policies
    #policy: none
  ingress:
    enabled: true
    annotations: {}
    path: /minio
    hosts:
      - caluma.chart-example.local
    tls: []
